postgres:
  image: postgres
  environment:
    - "POSTGRES_USER=seven_ten"
    - "POSTGRES_PASSWORD=seven_ten"
  ports:
    - "5432:5432"

seven_ten:
  dockerfile: Dockerfile
  build: ./
  environment:
    - "RAILS_ENV=docker_development"
    - "RACK_ENV=docker_development"
  links:
    - postgres:pg
  ports:
    - "443:443"
