version: '2'
services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_USER=seven_ten"
      - "POSTGRES_PASSWORD=seven_ten"
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  app:
    build:
      context: .
      args:
        RAILS_ENV: docker_development
    volumes:
      - ./:/rails_app
    ports:
      - "3000:80"
    environment:
      - "RAILS_ENV=docker_development"
      - "RACK_ENV=docker_development"
    links:
      - redis:redis
      - postgres:postgres

  sidekiq:
    build:
      context: .
      args:
        RAILS_ENV: docker_development
    command: ["/app/docker/start_sidekiq.sh"]
    volumes:
      - ./:/rails_app
    environment:
      - "RAILS_ENV=docker_development"
    links:
      - redis:redis
      - postgres:postgres


